---
title: "Vignette Widgets"
author: "Jay Hesselberth"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Widgets}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, echo=FALSE}
# set seed for reproducible widget id
if (requireNamespace("htmltools", quietly = TRUE)) {
  htmlwidgets::setWidgetIdSeed(42)
}
```

If you use htmlwidgets in pkgdown, use chunk option `out.width = '100%'` to ensure the widget spans the entire column.

### leaflet

```{r leaflet, out.width = '100%'}
library(leaflet)
  leaflet() %>%
  addTiles() %>%
  addMarkers(
  lng=174.768,
  lat=-36.852,
  popup="The birthplace of R"
)
```

### heatmaply

```{r heatmaply, out.width = '100%'}
library(heatmaply)
heatmaply(mtcars, k_row = 3, k_col = 2)
```

### DT

```{r dt, out.width = '100%'}
library(DT)
datatable(iris)
```

### plotly

```{r plotly, out.width = '100%'}
library(plotly)
plot_ly(midwest,
  x = ~percollege,
  color = ~state,
  type = "box"
)
```

```{r diagrammer, out.width = '100%'}
library(DiagrammeR)
grViz("
  digraph {
    layout = twopi
    node [shape = circle]
    A -> {B C D} 
  }")
```
